server:
  port: 8079
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/toy_db
    username: root
    password: password
    mapper-locations: classpath:mybatis/mapper/*.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  type-aliases-package: com.toy.toy_petsitter_back
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml