server:
  port: 8079
  servlet:
    encoding:
      charset: UTF-8
      force: true
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: true #경로 틀렸을때 /error로 이동

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/toy_db
    username: root
    password: password
    mapper-locations: classpath:mybatis/mapper/*.xml
  mail:
    host: smtp.naver.com
    port: 465 #587
    username: lyj3637@naver.com
    password: Wndls1907!
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

google:
  recaptcha:
    key:
      site: 6LelnLUlAAAAAECPwe7R9JadrtQzcK3K4CWUb9TR
      secret: 6LelnLUlAAAAALFU-Eby97vn24gfbaZ3ArHQRTQu
      url: https://www.google.com/recaptcha/api/siteverify

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  type-aliases-package: com.toy.toy_petsitter_back
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


secret:
  aeskey256: S&*@F2pd<#/dsSEc_t1!s&dcP^d@fL1@ #32자리
  ivspec: Gk_sfj#5%FspM0#+ #16자리


